baseURL = "https://alejandrocruzmartinez.com"
defaultContentLanguage = "es"
languageCode = "es"

title = "Alejandro Cruz Martínez"

theme = "gokarna"

publishDir = "public"

enableRobotsTXT = true

[menu]
    [[menu.main]]
        # Unique identifier for a menu item
        identifier = "posts"
        url = "/posts/"
        # You can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # You can add extra information after the name (HTML format is supported), such as icons
        post = ""
        # Display name
        name = "Posts"
        # Weights are used to determine the ordering
        weight = 1

    
    [[menu.main]]
        name = "Proyectos"
        url = "/projects/"
        weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "Etiquetas"
        url = "/tags/"
        weight = 3
    
    # [[menu.main]]
    #     identifier = "github"
    #     url = "https://github.com"
    #     weight = 4
        
    #     # We use feather-icons: https://feathericons.com/
    #     pre = "<span data-feather='github'></span>"

[params]
    # URL for the avatar on homepage
    avatarURL = "/images/me.jpg"

    # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
    avatarSize = ""

    # Description to display on homepage
    description = "Ingeniero de Ciberseguridad"

    # Accent color is displayed when you hover over <a> tags
    accentColor = "#0563bb"

    # You can use this to inject any HTML in the <head> tag.
    # Ideal usecase for this is to import custom js/css or add your analytics snippet
    customHeadHTML = ""

    # Keywords relevant for SEO
    metaKeywords = ["blog", "pwnedshell", "alejandro", "cruz", "martínez"]

    # If you want to display posts on the homepage, the options are
    # "popular" (order posts by weight), "recent" (order posts by date)
    # or "" (do not display, default option)
    showPostsOnHomePage = "recent"

    # Footer text
    footer = "PwnedShell"

    socialIcons = [
        {name = "twitter", url = "https://twitter.com/PwnedShell"},
        {name = "github", url = "https://github.com/PwnedShell"},
        {name = "linkedin", url = "https://www.linkedin.com/in/alejandro-cruz-martinez/"},
        {name = "gmail", url = "mailto:alejandro.cruz.martinez@protonmail.com"},
    ]

pygmentsStyle = "monokai"

[markup]
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 3
        ordered = false